name: Build
env:
  BREATHE_API_KEY: "some-api-key"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Set up cache
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/breathe.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Build and test with Rake
      run: |
        sudo apt-get update
        sudo apt-get install sqlite3 libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3 --path ./vendor/bundle
        bundle exec rake
